---

# - set_fact:
#     path_build: "{{ path_build | default('/tmp') }}"
#   tags: ["always"]

# - set_fact:
#     chroot_dir: '{{path_build}}/target'
#   tags: ["always"]

- command: apk add mkinitfs squashfs-tools
  tags: ["always"]

- name: lineinfile /etc/mkinitfs/features.d/network.modules virtio
  lineinfile:
    dest: /etc/mkinitfs/features.d/network.modules
    line: kernel/drivers/net/virtio_net.ko
  tags: ["always"]

- name: lineinfile /etc/mkinitfs/features.d/dhcp.files script
  lineinfile:
    dest: /etc/mkinitfs/features.d/dhcp.files
    line: /usr/share/udhcpc/default.script
    create: true
  tags: ["always"]

- name: lineinfile /etc/mkinitfs/features.d/dhcp.modules af_packet
  lineinfile:
    dest: /etc/mkinitfs/features.d/dhcp.modules
    line: kernel/net/packet/af_packet.ko
    create: true
  tags: ["always"]

- name: lineinfile /etc/mkinitfs/mkinitfs.conf featres
  lineinfile:
    dest: /etc/mkinitfs/mkinitfs.conf
    line: features="ata base bootchart cramfs ext2 ext3 ext4 xfs keymap kms raid scsi usb virtio squashfs network dhcp"
  tags: ["always"]

# squashfs
- name: export build initrd from remote to local
  command: mksquashfs modules/ /root/alpine-3.5-modules.squashfs -comp xz
  args:
    chdir: /lib
  tags: ["always"]

- name: export build initrd from remote to local
  fetch:
    src: /root/alpine-3.5-modules.squashfs
    dest: ../output-pxe-3.5.2/alpine-3.5-modules.squashfs
    flat: true
  tags: ["always"]

# initrd
- name: command mkinitfs /root/alpine-3.5-pxerd
  command: mkinitfs -o /root/alpine-3.5-pxerd
  tags: ["always"]

- name: export build initrd from remote to local
  fetch:
    src: /root/alpine-3.5-pxerd
    dest: ../output-pxe-3.5.2/alpine-3.5-pxerd
    flat: true
  tags: ["always"]


  
