---

# - set_fact:
#     path_build: "{{ path_build | default('/tmp') }}"
#   tags: ["always"]

# - set_fact:
#     chroot_dir: '{{path_build}}/target'
#   tags: ["always"]

- shell: |
    chroot {{chroot_dir}} sh -c 'uuid=$(uuidgen); printf "%s\n%s\n" "$uuid" "$uuid" | passwd root'
    chroot {{chroot_dir}} apk add python py2-pip
    chroot {{chroot_dir}} pip install --upgrade pip
    chroot {{chroot_dir}} pip install awscli
  tags: ["always"]
  # environment:
  #   http_proxy: '{{HTTP_PROXY}}'
