---

- set_fact:
    path_build: "{{ path_build | default('/tmp') }}"
  tags: ["always"]

- set_fact:
    chroot_dir: '{{path_build}}/target'
  tags: ["always"]

- shell: |
    chroot /tmp/target sh -c 'uuid=$(uuidgen); printf "${uuid}\n${uuid}\n" | passwd root'
  tags: ["always"]
