---

- set_fact:
    path_build: "{{ path_build | default('/tmp') }}"
  tags: ["always"]

- set_fact:
    chroot_dir: '{{path_build}}/target'
  tags: ["always"]

- shell: |
    chroot {{chroot_dir}} sh -c 'printf "admin\nadmin\n" | passwd admin'
    chroot {{chroot_dir}} sh -c 'printf "root\nroot\n" | passwd root'
  tags: ["always"]
