---

# Variables you might want to change
- set_fact:
    HTTP_PROXY: http://10.8.8.8:3142
  tags: ["always"]

- set_fact:
    version_major: 3
    version_minor: 5
    version_patch: 2
  tags: ["always"]

- set_fact:
    version: '{{version_major}}.{{version_minor}}.{{version_patch}}'
    version_major_minor: '{{version_major}}.{{version_minor}}'
  tags: ["always"]

# Don't default devices, make the user set them.
#- set_fact:
#    dev_alpine: sda
#    dev_alpine_eventual: sda

# Not sure packer runs this like a normal playbook, so defaulting values
# without using normal ansible precendence. Override these in the 
# required `playbook_TTTT.yml` file.
- set_fact:

    # Boot partition is 0 to `dev_alpine_boot_end`
    dev_alpine_boot_end: "{{ dev_alpine_boot_end | default('64MiB') }}"

    # Root partition is `dev_alpine_boot_end` to `dev_alpine_root_end`
    dev_alpine_root_end: "{{ dev_alpine_root_end | default('100%') }}"

    # Disable swap on primary drive
    has_swap: "{{ has_swap | default('false') }}"

    # Swap partition (if enabled) is `dev_alpine_root_end` to `dev_alpine_swap_end`
    dev_alpine_swap_end: "{{ dev_alpine_swap_end | default('100%') }}"

    # Path to build in
    path_build: "{{ path_build | default('/tmp') }}"

    # Username to use for build and after
    user_base: "{{ user_base | default('admin') }}"

    # Hostname for the box
    hostname: "{{ hostname | default('alpvirt') }}"

    # Load the public key from disk
    pubkey: "{{ pubkey | default(lookup('file', 'id_rsa_alpine.pub')) }}"

    #file_iso: alpine-standard-{{version}}-x86_64.iso
  tags: ["always"]


# Variables based on the tags (need to be defaulted)

- set_fact:
    is_aws: false
    is_vbox: false
    is_surrogate: false
  tags: ["always"]

- set_fact:
    is_aws: true
  tags: ["aws"]

- set_fact:
    is_vbox: true
  tags: ["vbox"]

- set_fact:
    is_surrogate: true
  tags: ["surrogate", "aws"]



# Steps

- name: 'template /etc/apk/repositories etc-apk-repositories.j2'
  tags: ["vbox"]
  template: 
    src: etc-apk-repositories.j2
    dest: /etc/apk/repositories

- name: "add install deps"
  tags: ["vbox"]
#  apk:
#    name: e2fsprogs, syslinux, parted, build-base
  shell: apk add --no-cache e2fsprogs syslinux parted


- name: setup alpine disk
  tags: ["always"]
  shell: |
    set -uex
    parted /dev/{{dev_alpine}} -s mktable msdos
    parted /dev/{{dev_alpine}} -sa optimal -- mkpart primary ext4 0% {{dev_alpine_boot_end}}
    parted /dev/{{dev_alpine}} -s set 1 boot on
    parted /dev/{{dev_alpine}} -sa optimal -- mkpart primary ext4 {{dev_alpine_boot_end}} {{dev_alpine_root_end}}
    parted /dev/{{dev_alpine}} print list
  args:
    chdir: '{{ path_build }}'

- name: setup alpine disk swap
  tags: ["always"]
  shell: |
    set -uex
    parted /dev/{{dev_alpine}} -sa optimal -- mkpart primary linux-swap {{dev_alpine_root_end}} {{dev_alpine_swap_end}}
    mkswap /dev/{{dev_alpine}}2
  args:
    chdir: '{{ path_build }}'
  when: has_swap

#setup-disk -m sys -k virtgrsec -s 0 -v /mnt/target /dev/sda

- name: mount alpine disk
  tags: ["always"]
  shell: |
    mkdir target
    mkdir source
    mke2fs -t ext4 /dev/{{dev_alpine}}1
    mke2fs -t ext4 /dev/{{dev_alpine}}2
    mount -t ext4 /dev/{{dev_alpine}}2 target
    mkdir -p target/boot
    mount -t ext4 /dev/{{dev_alpine}}1 target/boot
  args:
    chdir: '{{ path_build }}'

# - name: 'get release iso for debian surrogate installs'
#   tags: ["surrogate","aws"]
#   get_url:    
#     url: http://dl-cdn.alpinelinux.org/alpine/v{{version_major_minor}}/releases/x86_64/{{file_iso}}
#     dest: '{{ path_build }}/{{file_iso}}'

# - name: extract iso
#   shell: |
#     set -uex
#     mount -o loop {{file_iso}} source
#     cp -av source/boot target
#     rm -f target/boot/modloop-grsec
#     rm -f target/boot/modloop-virtgrsec
#     rm -rf target/boot/syslinux
#     umount source
#   args:
#     chdir: '{{ path_build }}'
#   tags: ["surrogate","aws"]

- shell: 'blkid -o value /dev/{{dev_alpine}}2'
  register: blkid_dev
  tags: ["always"]

- debug: var=blkid_dev.stdout_lines
  tags: ["always"]

- set_fact:
    blk_uuid: '{{ blkid_dev.stdout_lines[0] }}'
  tags: ["always"]

# Chroot

- set_fact:
    chroot_dir: '{{path_build}}/target'
  tags: ["always"]

# - get_url:    
#     url: http://dl-cdn.alpinelinux.org/alpine/v{{version_major_minor}}/releases/x86_64/alpine-minirootfs-{{version}}-x86_64.tar.gz
#     dest: '{{ path_build }}/alpine-minirootfs-3.5.2-x86_64.tar.gz'
#   tags: ["always"]

# - unarchive:
#     src: '{{ path_build }}/alpine-minirootfs-3.5.2-x86_64.tar.gz'
#     dest: '{{ chroot_dir }}'


- copy: 
    src: chroot_run.sh
    dest: '{{chroot_dir}}/chroot_run.sh'
    mode: 0755
  tags: ["always"]

- file:
    path: '{{chroot_dir}}{{item}}'
    state: directory
    mode: 0755
  with_items:
    - '/root'
    - '/boot'
    - '/etc/network'
    - '/etc/init.d'
    - '/etc/apk'
    - '/proc'
    - '/sys'
    - '/dev'
  tags: ["always"]

- name: system setup for chroot
  tags: ["always"]
  shell: |
    set -ue
    mount -t proc none {{chroot_dir}}/proc
    mount -o bind /sys {{chroot_dir}}/sys
    mount -o bind /dev {{chroot_dir}}/dev
  args:
    chdir: '{{path_build}}'

- name: copy etc-init.d-network-debug /etc/init.d/netdebug
  copy:
    src: ./etc-init.d-network-debug
    dest: '{{chroot_dir}}/etc/init.d/netdebug'
    mode: 0755
  tags: ["always"]

- name: 'template /etc/apk/repositories etc-apk-repositories.j2'
  tags: ["always"]
  template: 
    src: etc-apk-repositories.j2
    dest: '{{chroot_dir}}/etc/apk/repositories'

- name: chroot system setup
  tags: ["always"]
  shell: |
    set -ue
    # Config
    echo "ipv6" >> {{chroot_dir}}/etc/modules
    echo "{{hostname}}" > {{chroot_dir}}/etc/hostname
    mkdir -p {{chroot_dir}}/home/{{user_base}}/.ssh
    echo '{{pubkey}}' > {{chroot_dir}}/home/{{user_base}}/.ssh/authorized_keys
    cp /etc/resolv.conf {{chroot_dir}}/etc/
    echo 'alpine virt' > {{chroot_dir}}/etc/motd
  args:
    chdir: '{{path_build}}'

- name: 'add vbox intel e1000 driver module'
  tags: ["vbox"]
  lineinfile:
    dest: '{{chroot_dir}}/etc/modules'
    line: 'e1000'


- name: get apk static for debian
  tags: ["always"]
  get_url:    
    url: http://dl-cdn.alpinelinux.org/alpine/v{{version_major_minor}}/main/x86_64/apk-tools-static-2.6.8-r2.apk
    dest: '{{ path_build }}/apk-tools-static-2.6.8-r2.tgz'
  environment:
    http_proxy: '{{HTTP_PROXY}}'

- name: extract apk static
  tags: ["always"]
  unarchive:
    src: '{{path_build}}/apk-tools-static-2.6.8-r2.tgz'
    dest: '{{path_build}}'
    remote_src: yes

- name: Install packages with apk static
  tags: ["always"]
  command: '{{path_build}}/sbin/apk.static --no-cache -X http://dl-cdn.alpinelinux.org/alpine/v{{version_major_minor}}/main -U --allow-untrusted --root {{chroot_dir}} --initdb add alpine-base linux-virtgrsec iproute2 iptables ip6tables iputils e2fsprogs coreutils util-linux syslinux sudo bash openssh dhcpcd curl'
  environment:
    http_proxy: '{{HTTP_PROXY}}'

#dropbear dropbear-scp

- name: remove kernel bits
  tags: ["always"]
  file:
    path: '{{item}}'
    state: absent
  with_items:
    - '{{chroot_dir}}/boot/libutil.c32'
    - '{{chroot_dir}}/boot/mboot.c32'
    - '{{chroot_dir}}/boot/menu.c32'
    - '{{chroot_dir}}/boot/vesamenu.c32'
    - '{{chroot_dir}}/boot/extlinux.conf.old'


# - name: Install vbox guest packages
#   tags: ["vbox"]
#   command: |
#     mkdir /mnt/iso
#     mount -o loop,ro VBoxGuestAdditions /mnt/iso
#     sh /mnt/VBoxLinuxAdditions.run
#     umount /mnt/iso


- name: 'template /etc/fstab etc-fstab.j2'
  tags: ["always"]
  template: 
    src: etc-fstab.j2
    dest: '{{chroot_dir}}/etc/fstab'

- name: 'template /boot/extlinux.conf extlinux.conf.j2'
  tags: ["always"]
  template: 
    src: extlinux.conf.j2
    dest: '{{chroot_dir}}/boot/extlinux.conf'

- name: 'extlinux for chroot'
  tags: ["vbox"]
  command: extlinux --install {{chroot_dir}}/boot

- name: 'extlinux mbr'
  tags: ["vbox"]
  shell: cat /usr/share/syslinux/mbr.bin > /dev/{{dev_alpine}}

- name: 'extlinux for chroot'
  tags: ["surrogate","aws"]
  command: chroot {{chroot_dir}} extlinux --install /boot

- name: chroot
  tags: ["always"]
  command: chroot {{chroot_dir}} /chroot_run.sh
  args:
    chdir: '{{path_build}}'

- name: 'template /etc/hosts etc-hosts.j2'
  tags: ["always"]
  template:
    src: ./etc-hosts.j2
    dest: '{{chroot_dir}}/etc/hosts'

- name: 'template /etc/network/interfaces etc-network-interfaces.j2'
  tags: ["always"]
  template:
    src: ./etc-network-interfaces.j2
    dest: '{{chroot_dir}}/etc/network/interfaces'

- name: Turn on OpenRC logging (not dates still!)
  lineinfile:
    dest: '{{chroot_dir}}/etc/rc.conf'
    regexp: ^\s*#?\s*rc_logger=
    line: rc_logger="YES"
  tags: ["always"]


# sshd
- lineinfile:
    dest: '{{chroot_dir}}/etc/ssh/sshd_config'
    line: PermitTunnel yes
  tags: ["always"]
- lineinfile:
    dest: '{{chroot_dir}}/etc/ssh/sshd_config'
    line: PasswordAuthentication no
  tags: ["aws"]
- lineinfile:
    dest: '{{chroot_dir}}/etc/ssh/sshd_config'
    line: PermitRootLogin no
  tags: ["always"]
- lineinfile:
    dest: '{{chroot_dir}}/etc/ssh/sshd_config'
    line: UseDNS no
  tags: ["always"]


- name: 'lineinfile /etc/sudoers base user'
  tags: ["always"]
  lineinfile:
    dest: '{{chroot_dir}}/etc/sudoers'
    line: '{{user_base}} ALL = NOPASSWD: ALL'



# wget 
# apk update
# apk add iproute2 grep gzip jq aiputils wget curl coreutils tar bash e2fsprogs procps pstree psutils gawk sed vim less groff python2 py2-pip
# pip install --upgrade pip
# pip install awscli