
---
- hosts: alpine
  
  vars:
    dev_alpine: sda
    dev_alpine_eventual: sda
    hostname: alpbox

  become: yes

  tasks:

    - include: alpine_vars.yml
    - include: alpine_build_pxe.yml

#    - name: 'shutdown vbox'
#      command: halt -d 5
