
---
- hosts: alpine
  
  vars:
    dev_alpine: sda
    dev_alpine_eventual: sda
    hostname: alpbox

  become: yes

  tasks:

    - include: alpine_vars.yml
    - include: alpine_build.yml
    - include: alpine_build_builder.yml

#    - name: 'shutdown vbox'
#      shell: |
#        sync
#        sync
#        sleep 1
#        halt -d 5
