
---
- hosts: alpine
  
  vars:
    path_build: /tmp
    dev_alpine: xvdf
    file_iso: alpine-virt-3.5.2-x86_64.iso
    pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqGxLbtArl7UE1noY1tNpRxxQUFCTiSUzFBtT/TYvb8ZWn+wy6dgM5yh6jWQl/0ZCLgqF8tNZCemJ64KfL1+5QZAa027+2YqJuSqO0kYZk6fJ7o67P+zEny27NbAnERBLoTde0btGVd1ZneDTCfLROmbTJGKA9EyZ98CyCfBJNqYRllsNrqOfAKegxwSrRNYepuq3eGWKMfTvRECHq0XdTRdcQ7HpF+rZUPqnWwOv8zQZ8kWwepiqk5dQryfusvkj6EZHdW8ftc2ExOCCY9Mo/Zi2ggWvVlIdCRuV8X/7Ki4qVVohOpNFbuJr8HRDSq0q3kxkVdxRQkAgXLG1+tM2DaRD22F1r7KJEncU1K3Gq0CDxYQkfjQNcyRsn3/mJ3dphS0WskuL5xHxex1O3XTIlfqI0l8dSxdscDGtXiwF2+fccxCzOzovGauzGWrtCNVwNkepPt632AkGna379Qpms6HbZGnbr1LHA36OZ6xAY8w8RpkEFG34LVcH0Dfotsp8= admin@alpine
  become: yes

  tasks:

  - name: testing
    command: echo testing
  
  - name: setup
    shell: |
      set -uex
      mke2fs -t ext4 /dev/{{dev_alpine}}
      mkdir target
      mkdir source
      mount /dev/{{dev_alpine}} target
    args:
      chdir: '{{ path_build }}'

  - get_url:    
      url: http://dl-cdn.alpinelinux.org/alpine/v3.5/releases/x86_64/{{file_iso}}
      dest: '{{ path_build }}/{{file_iso}}'

  - get_url:    
      url: http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/apk-tools-static-2.6.8-r2.apk
      dest: '{{ path_build }}/apk-tools-static-2.6.8-r2.apk'

  - name: extract
    shell: |
      set -uex
      mount -o loop {{file_iso}} source
      cp -av source/boot target
      umount source
    args:
      chdir: '{{ path_build }}'

  - name: grub
    shell: |
      set -uex
      mkdir -p target/boot/grub
      touch target/boot/grub/grub.conf
      cd target/boot/grub/
      ln -sf grub.conf menu.lst
    args:
      chdir: '{{ path_build }}'

  - template: 
      src: grub.j2
      dest: '{{ path_build }}/target/boot/grub/grub.conf'

  - copy: 
      src: chroot_run.sh
      dest: '{{ path_build }}/target/chroot_run.sh'
      mode: 0755

  - set_fact:
      chroot_dir: '{{ path_build }}/target'

  - name: chroot
    shell: |
      set -uex
      mkdir {{chroot_dir}}/root/
      mkdir {{chroot_dir}}/etc/
      mkdir {{chroot_dir}}/etc/apk
      mkdir {{chroot_dir}}/etc/network
      mkdir {{chroot_dir}}/proc/
      mkdir {{chroot_dir}}/sys/
      mkdir {{chroot_dir}}/dev/
      echo "ipv6" >> {{chroot_dir}}/etc/modules
      echo "awsbuild" > {{chroot_dir}}/etc/hostname
      mkdir -p {{chroot_dir}}/admin/.ssh
      echo '{{pubkey}}' > {{chroot_dir}}/admin/.ssh/authorized_keys
      cp /etc/resolv.conf {{chroot_dir}}/etc/
      tar -xzf apk-tools-static-2.6.8-r2.apk
      ./sbin/apk.static -X http://dl-cdn.alpinelinux.org/alpine/v3.5/main -U --allow-untrusted --root {{chroot_dir}} --initdb add alpine-base
      mount -t proc none {{chroot_dir}}/proc
      mount -o bind /sys {{chroot_dir}}/sys
      mknod -m 666 {{chroot_dir}}/dev/full c 1 7
      mknod -m 666 {{chroot_dir}}/dev/ptmx c 5 2
      mknod -m 644 {{chroot_dir}}/dev/random c 1 8
      mknod -m 644 {{chroot_dir}}/dev/urandom c 1 9
      mknod -m 666 {{chroot_dir}}/dev/zero c 1 5
      mknod -m 666 {{chroot_dir}}/dev/tty c 5 0
      rm -f {{chroot_dir}}/dev/null
      mknod -m 666 {{chroot_dir}}/dev/null c 1 3
      chroot {{chroot_dir}} /chroot_run.sh
    args:
      chdir: '{{ path_build }}'

  - template:
      src: ./etc-hosts.j2
      dest: '{{chroot_dir}}/etc/hosts'

  - template:
      src: ./etc-network-interfaces.j2
      dest: '{{chroot_dir}}/etc/network/interfaces'

# wget 
# apk update
# apk add iproute2 grep gzip jq aiputils wget curl coreutils tar bash e2fsprogs procps pstree psutils gawk sed vim less groff python2 py2-pip
# pip install --upgrade pip
# pip install awscli