
---
- hosts: alpine
  
  vars:
    path_build: /tmp
    dev_alpine: xvdf
    dev_alpine_eventual: xvda
    dev_alpine_boot_end: 64MiB
    dev_alpine_root_end: 100%
    hostname: alpaws
    user_base: admin

  become: yes

  tasks:
    - include: alpine_build.yml
