
---
- hosts: alpine
  
  vars:
    dev_alpine: sda
    dev_alpine_eventual: sda
    hostname: alpbox

  become: yes

  tasks:

    - include: alpine_build.yml

    - include: alpine_build_vbox.yml

    - command: sync
      tags: ['always']
    - command: sync
      tags: ['always']
    - command: sleep 5
      tags: ['always']
    - name: 'shutdown vbox'
      command: halt -d 1
      tags: ['always']
